image: microsoft/dotnet:latest
image: docker:latest

stages:
    - build
    - test
    - docker

variables:
    test: "Essence.Communication.UnitTests"


before_script:
    - "dotnet MicroServices/Essence.Communication.Service/Essence.Communication.Api/restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script:
        - "dotnet MicroServices/Essence.Communication.Service/Essence.Communication.UnitTests/test"

docker:
    stage: docker
    script:
        - "docker info"