image: microsoft/dotnet:latest
image: docker:latest

stages:
    - build
    - test
    - docker

variables:
    test: "MicroServices/Essence.Communication.Service/Essence.Communication.UnitTests"


before_script:
    - "cd MicroServices/Essence.Communication.Service/Essence.Communication.Api"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script:
        - "cd $test"
        - "dotnet test"

docker:
    stage: docker
    script:
        - "docker info"