stages:
    - build
    - test
    - docker

variables:
    test: "MicroServices/Essence.Communication.Service/Essence.Communication.UnitTests/Essence.Communication.UnitTests.csproj"


before_script:
    - "dotnet restore ./MicroServices/Essence.Communication.Service/Essence.Communication.Api/Essence.Communication.Api.csproj"

build:
    stage: build
    image: microsoft/dotnet:latest    
    script:
        - "dotnet build ./MicroServices/Essence.Communication.Service/Essence.Communication.Api/Essence.Communication.Api.csproj"

test:
    stage: test
    image: microsoft/dotnet:latest    
    script:
        - "dotnet test $test"

docker:
    stage: docker
    image: docker:latest
    services:
        - docker:dind
    script:
        - "docker build -t ./MicroServices/Essence.Communication.Service/Essence.Communication.Api/Dockerfile"