stages:
    - build
    - test
    - docker
    - deploy

variables:
    test: "MicroServices/Essence.Communication.Service/Essence.Communication.UnitTests/Essence.Communication.UnitTests.csproj"

build:
    stage: build
    image: microsoft/dotnet:latest
    script:
        - "dotnet restore ./MicroServices/Essence.Communication.Service/Essence.Communication.Api/Essence.Communication.Api.csproj"    
        - "dotnet build ./MicroServices/Essence.Communication.Service/Essence.Communication.Api/Essence.Communication.Api.csproj"

test:
    stage: test
    image: microsoft/dotnet:latest    
    script:
        - "dotnet test $test"

docker:
    stage: docker
    image: docker:latest
    services:
        - docker:dind
    script:
        - echo "docker image"
        - "docker build -f ./MicroServices/Essence.Communication.Service/Essence.Communication.Api/Dockerfile.original"
        
deploy:
    stage: deploy
    variables:
        AWS_DEFAULT_REGION: "ap-sydney-2"
    script:
        - "cd MicroServices"
        - echo $AWS_ACCESS_KEY_ID
        - echo $AWS_SECRET_ACCESS_KEY
        - echo $PROD_LOAD_BALANCER_URL