image: microsoft/dotnet:latest

stages:
    - build
    - test

variables:
    test: "Essence.Communication.UnitTests"

before_script:
    - "cd MicroServices/Essence.Communication.Service/Essence.Communication.Api"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script:
        - "cd ../Essence.Communication.UnitTests"
        - "cd $test"
        - "dotnet test"
